export type AssetSeed = {
  symbol: string
  name: string
  assetType: 'STOCK' | 'CRYPTO' | 'COMMODITY'
  description?: string
}

export const STOCK_TICKERS: string[] = [
  'NVDA',
  'MSFT',
  'AAPL',
  'AMZN',
  'META',
  'AVGO',
  'GOOGL',
  'GOOG',
  'TSLA',
  'BRK.B',
  'JPM',
  'WMT',
  'ORCL',
  'LLY',
  'V',
  'MA',
  'NFLX',
  'XOM',
  'COST',
  'JNJ',
  'HD',
  'PLTR',
  'PG',
  'BAC',
  'ABBV',
  'CVX',
  'KO',
  'AMD',
  'GE',
  'TMUS',
  'CSCO',
  'WFC',
  'CRM',
  'PM',
  'IBM',
  'UNH',
  'MS',
  'INTU',
  'GS',
  'ABT',
  'LIN',
  'MCD',
  'DIS',
  'AXP',
  'RTX',
  'MRK',
  'NOW',
  'CAT',
  'PEP',
  'T',
  'TMO',
  'UBER',
  'VZ',
  'BKNG',
  'QCOM',
  'ISRG',
  'SCHW',
  'TXN',
  'C',
  'ACN',
  'GEV',
  'BLK',
  'BA',
  'AMGN',
  'SPGI',
  'ADBE',
  'BSX',
  'ETN',
  'SYK',
  'AMAT',
  'ANET',
  'NEE',
  'DHR',
  'GILD',
  'PGR',
  'TJX',
  'HON',
  'DE',
  'BX',
  'PFE',
  'COF',
  'KKR',
  'UNP',
  'PANW',
  'LOW',
  'APH',
  'LRCX',
  'ADP',
  'MU',
  'COP',
  'CMCSA',
  'KLAC',
  'VRTX',
  'MDT',
  'SNPS',
  'CRWD',
  'NKE',
  'ADI',
  'WELL',
  'SBUX'
]

export const CRYPTO_ASSETS: AssetSeed[] = [
  { symbol: 'BTC/USD', name: 'Bitcoin', assetType: 'CRYPTO' },
  { symbol: 'ETH/USD', name: 'Ethereum', assetType: 'CRYPTO' },
  { symbol: 'XRP/USD', name: 'XRP', assetType: 'CRYPTO' },
  { symbol: 'BNB/USD', name: 'BNB', assetType: 'CRYPTO' },
  { symbol: 'SOL/USD', name: 'Solana', assetType: 'CRYPTO' },
  { symbol: 'DOGE/USD', name: 'Dogecoin', assetType: 'CRYPTO' },
  { symbol: 'ADA/USD', name: 'Cardano', assetType: 'CRYPTO' },
  { symbol: 'TRX/USD', name: 'TRON', assetType: 'CRYPTO' },
  { symbol: 'HYPE/USD', name: 'Hyperliquid', assetType: 'CRYPTO' },
  { symbol: 'XLM/USD', name: 'Stellar', assetType: 'CRYPTO' },
  { symbol: 'SUI/USD', name: 'Sui', assetType: 'CRYPTO' },
  { symbol: 'LINK/USD', name: 'Chainlink', assetType: 'CRYPTO' },
  { symbol: 'HBAR/USD', name: 'Hedera', assetType: 'CRYPTO' },
  { symbol: 'AVAX/USD', name: 'Avalanche', assetType: 'CRYPTO' },
  { symbol: 'BCH/USD', name: 'Bitcoin Cash', assetType: 'CRYPTO' },
  { symbol: 'SHIB/USD', name: 'Shiba Inu', assetType: 'CRYPTO' },
  { symbol: 'LTC/USD', name: 'Litecoin', assetType: 'CRYPTO' },
  { symbol: 'TON/USD', name: 'Toncoin', assetType: 'CRYPTO' },
  { symbol: 'LEO/USD', name: 'UNUS SED LEO', assetType: 'CRYPTO' },
  { symbol: 'DOT/USD', name: 'Polkadot', assetType: 'CRYPTO' },
  { symbol: 'UNI/USD', name: 'Uniswap', assetType: 'CRYPTO' },
  { symbol: 'USDE/USD', name: 'Ethena USDe', assetType: 'CRYPTO' },
  { symbol: 'XMR/USD', name: 'Monero', assetType: 'CRYPTO' }
]

export const COMMODITY_ASSETS: AssetSeed[] = [
  { symbol: 'BRENT_OIL', name: 'Crude Oil (Brent)', assetType: 'COMMODITY' },
  { symbol: 'WTI_OIL', name: 'Crude Oil (WTI)', assetType: 'COMMODITY' },
  { symbol: 'NAT_GAS', name: 'Natural Gas', assetType: 'COMMODITY' },
  { symbol: 'GOLD', name: 'Gold', assetType: 'COMMODITY' },
  { symbol: 'SILVER', name: 'Silver', assetType: 'COMMODITY' },
  { symbol: 'COPPER', name: 'Copper', assetType: 'COMMODITY' },
  { symbol: 'ALUMINUM', name: 'Aluminum', assetType: 'COMMODITY' },
  { symbol: 'IRON_ORE', name: 'Iron Ore', assetType: 'COMMODITY' },
  { symbol: 'COAL', name: 'Coal', assetType: 'COMMODITY' },
  { symbol: 'WHEAT', name: 'Wheat', assetType: 'COMMODITY' },
  { symbol: 'CORN', name: 'Corn', assetType: 'COMMODITY' },
  { symbol: 'SOYBEAN', name: 'Soybeans', assetType: 'COMMODITY' },
  { symbol: 'COTTON', name: 'Cotton', assetType: 'COMMODITY' },
  { symbol: 'PALLADIUM', name: 'Palladium', assetType: 'COMMODITY' },
  { symbol: 'PLATINUM', name: 'Platinum', assetType: 'COMMODITY' },
  { symbol: 'NICKEL', name: 'Nickel', assetType: 'COMMODITY' },
  { symbol: 'ZINC', name: 'Zinc', assetType: 'COMMODITY' },
  { symbol: 'LEAD', name: 'Lead', assetType: 'COMMODITY' },
  { symbol: 'SUGAR', name: 'Sugar', assetType: 'COMMODITY' },
  { symbol: 'COFFEE', name: 'Coffee', assetType: 'COMMODITY' },
  { symbol: 'COCOA', name: 'Cocoa', assetType: 'COMMODITY' },
  { symbol: 'RICE', name: 'Rice', assetType: 'COMMODITY' },
  { symbol: 'RUBBER', name: 'Rubber', assetType: 'COMMODITY' },
  { symbol: 'LUMBER', name: 'Lumber', assetType: 'COMMODITY' },
  { symbol: 'URANIUM', name: 'Uranium', assetType: 'COMMODITY' }
]
