service: match-processor

provider:
  name: aws
  runtime: nodejs18.x
  stage: local
  region: us-east-1

functions:
  processMatches:
    handler: dist/index.handler

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566
    lambda:
      mountCode: true
    docker:
      sudo: false
    skipImagePull: true
